version: '3'
services:
  ko-js:
    build: .
    hostname: "kojs_sandbox"
    ports:
      - "15100-15109:15100-15109/udp"
      - "15001:15001/udp"
    networks:
      application:
        ipv4_address: 10.0.0.50
    restart: always
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /container/ko-js/mongo:/data/db
    networks:
      application:
        ipv4_address: 10.0.0.51
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  redis:
    image: "redis:alpine"
    networks:
      application:
        ipv4_address: 10.0.0.52
networks:
  application:
    external:
      name: application