module.exports = {
  RIGHTEAR: 0,
  HEAD: 1,
  LEFTEAR: 2,
  NECK: 3,
  BREAST: 4,
  SHOULDER: 5,
  RIGHTHAND: 6,
  WAIST: 7,
  LEFTHAND: 8,
  RIGHTRING: 9,
  LEG: 10,
  LEFTRING: 11,
  GLOVE: 12,
  FOOT: 13,
  RESERVED: 14,


  ItemSlot1HEitherHand: 0,
  ItemSlot1HRightHand: 1,
  ItemSlot1HLeftHand: 2,
  ItemSlot2HRightHand: 3,
  ItemSlot2HLeftHand: 4,
  ItemSlotPauldron: 5,
  ItemSlotPads: 6,
  ItemSlotHelmet: 7,
  ItemSlotGloves: 8,
  ItemSlotBoots: 9,
  ItemSlotEarring: 10,
  ItemSlotNecklace: 11,
  ItemSlotRing: 12,
  ItemSlotShoulder: 13,
  ItemSlotBelt: 14,
  ItemSlotBag: 25,
  ItemSlotCospreGloves: 100,
  ItemSlotCosprePauldron: 105,
  ItemSlotCospreHelmet: 107,
  ItemSlotCospreWings: 110,
  ItemSlotCospreFairy: 111
}