module.exports = {
  ZONE_KARUS: 1,
  ZONE_ELMORAD: 2,
  ZONE_KARUS2: 5,
  ZONE_KARUS3: 6,
  ZONE_ELMORAD2: 7,
  ZONE_ELMORAD3: 8,
  ZONE_KARUS_ESLANT: 11,
  ZONE_ELMORAD_ESLANT: 12,
  ZONE_KARUS_ESLANT2: 13,
  ZONE_KARUS_ESLANT3: 14,
  ZONE_ELMORAD_ESLANT2: 15,
  ZONE_ELMORAD_ESLANT3: 16,
  ZONE_MORADON: 21,
  ZONE_MORADON2: 22,
  ZONE_MORADON3: 23,
  ZONE_MORADON4: 24,
  ZONE_MORADON5: 25,
  ZONE_DELOS: 30,
  ZONE_BIFROST: 31,
  ZONE_DESPERATION_ABYSS: 32,
  ZONE_HELL_ABYSS: 33,
  ZONE_DRAGON_CAVE: 34,
  ZONE_ARENA: 48,
  ZONE_ORC_ARENA: 51,
  ZONE_BLOOD_DON_ARENA: 52,
  ZONE_GOBLIN_ARENA: 53,
  ZONE_CAITHAROS_ARENA: 54,
  ZONE_FORGOTTEN_TEMPLE: 55,
  ZONE_LOST_TEMPLE: 56,

  ZONE_BATTLE: 61, // Napies Gorge
  ZONE_BATTLE2: 62, // Alseids Prairie
  ZONE_BATTLE3: 63, // Nieds Triangle
  ZONE_BATTLE4: 64, // Nereid's Island
  ZONE_BATTLE5: 65, // Zipang
  ZONE_BATTLE6: 66, // Oreads

  ZONE_NAPIES_GORDE: 61,
  ZONE_ALSEIDS_PRAIRIE: 62,
  ZONE_NIEDS_TRIANGLE: 63,
  ZONE_NEREIDSISLAND: 64,
  ZONE_ZIPANG: 65,
  ZONE_OREADS: 66,

  ZONE_SNOW_BATTLE: 69,
  ZONE_RONARK_LAND: 71,
  ZONE_ARDREAM: 72,
  ZONE_RONARK_LAND_BASE: 73,
  ZONE_KROWAZ_DOMINION: 75,
  ZONE_CLAN_WAR: 77,
  ZONE_NEW_RONARK_EVENT: 78,

  ZONE_MONSTER_SQUAD1: 81,
  ZONE_MONSTER_SQUAD2: 82,
  ZONE_MONSTER_SQUAD3: 83,

  ZONE_BORDER_DEFENSE_WAR: 84,
  ZONE_CHAOS_DUNGEON: 85,
  ZONE_UNDER_THE_CASTLE: 86,
  ZONE_JURAD_MOUNTAIN: 87,
  ZONE_PRISON: 92,
  ZONE_ISILOON_ARENA: 93,
  ZONE_FELANKOR_ARENA: 94,
  ZONE_WINNER_CASTLE: 97,
  ZONE_WINNER_CASTLE2: 98,
  ZONE_OLD_MORADON: 91
}


Object.keys(module.exports).forEach(x => module.exports[module.exports[x]] = x);