database:
  uri: mongodb://127.0.0.1:27017/knight-online
  options:
    useNewUrlParser: true
    useCreateIndex: true

redis:
  host: '127.0.0.1'
  port: 6379

web:
  ip: 192.168.1.51
  port: 15000

defaults:
  account: true
  item: true
  npc: true
  server: true
  set_item: true
  setting: true
  object: true

loginServer:
  ip: 192.168.1.51
  ports: 
    - 15100
    - 15101
    - 15102
    - 15103
    - 15104
    - 15105
    - 15106
    - 15107
    - 15108
    - 15109
  ftp: 
    host: localhost
    dir: /
  otp: 'knightonline'
  maxOTPTry: 5
  versions:
    - version: 2228
      fileName: none

gameServer:
  ip: 192.168.1.51
  ports: 
    - 15001
  clientExeVersion: 2228
  
testClient:
  ip: '127.0.0.1'
  port: 15100
  version: 2228
  user: 'test'
  password: '1'
  server: 'TEST|SERVER 1'