database:
  uri: mongodb://localhost:27017/knight-online
  options:

loginServer:
  port: 15100
  ip: 0.0.0.0
  ftp: 
    host: localhost
    dir: /
  servers:
    - ip: 127.0.0.1
      lanip: 127.0.0.1
      name: TEST SERVER
      king:
        karus: karus_king
        elmorad: elmorad_king
      notice:
        karus: 'karus notice'
        elmorad: 'elmorad notice'