database:
  uri: mongodb://localhost:27017/knight-online
  options:

redis:
  host: '127.0.0.1'
  port: 6379

loginServer:
  ports: 
    #- 15100
    - 15101
    - 15102
    - 15103
    - 15104
    - 15105
    - 15106
    - 15107
    - 15108
    - 15109
  ip: 0.0.0.0
  ftp: 
    host: localhost
    dir: /