database:
  uri: mongodb://travis:test@127.0.0.1:27017/testdb
  options:
    useNewUrlParser: true
    useCreateIndex: true

redis:
  host: '127.0.0.1'
  port: 6379

  
defaults:
  account: true
  item: false
  npc: true
  server: true
  set_item: true
  setting: true