const csvLoader = require('../utils/csv_loader');

module.exports = async db => {
  await csvLoader({
    file: 'monster',
    modelName: 'Monster',
    expected: 826,
    transfer: {
      sSid: "id",
      strName: "name",
      sPid: "pid",
      sSize: "size",
      iWeapon1: "weapon1",
      iWeapon2: "weapon2",
      byGroup: "group",
      byActType: "actType",
      byType: "type",
      byFamily: "family",
      byRank: "rank",
      byTitle: "title",
      iSellingGroup: "sellingGroup",
      sLevel: "level",
      iExp: "exp",
      iLoyalty: "loyalty",
      iHpPoint: "hp",
      sMpPoint: "mp",
      sAtk: "attack",
      sAc: "ac",
      sHitRate: "hitRate",
      sEvadeRate: "evadeRate",
      sDamage: "damage",
      sAttackDelay: "attackDelay",
      bySpeed1: "speed1",
      bySpeed2: "speed2",
      sStandtime: "standtime",
      iMagic1: "magic1",
      iMagic2: "magic2",
      iMagic3: "magic3",
      sFireR: "fireR",
      sColdR: "coldR",
      sLightningR: "lightningR",
      sMagicR: "magicR",
      sDiseaseR: "diseaseR",
      sPoisonR: "poisonR",
      sBulk: "bulk",
      byAttackRange: "attackRange",
      bySearchRange: "searchRange",
      byTracingRange: "tracingRange",
      iMoney: "money",
      sItem: "item",
      byDirectAttack: "directAttack",
      byMagicAttack: "magicAttack",
      byMoneyType: "moneyType",
      sSpeed: "speed"
    },
    db
  })
}